blag/__init__.py
from flask import Flask, send_from_directory, request, g, current_app
from flask_login import LoginManager, current_user
from flask_principal import Principal, identity_changed, Identity
from flask_sqlalchemy import SQLAlchemy
from jinja2 import FileSystemLoader
from logging import getLogger
from os import path
from sqlalchemy_defaults import make_lazy_configured

import logging.config
import os
import sqlalchemy
import textwrap
import ujson as json
import yaml

from ._flask_porridge import Porridge

make_lazy_configured(sqlalchemy.orm.mapper)

db = SQLAlchemy()
login_manager = LoginManager()
principal = Principal()
porridge = Porridge()

_logger = getLogger('blag')

def create_app(**extra_config):
    app = Flask('blag')
    _configure_app(app, **extra_config)
    _init_logging(app)

    # register extensions
    db.init_app(app)
    login_manager.init_app(app)
    principal.init_app(app)
    porridge.init_app(app)

    # Set up login stuff
    from .auth import load_user
    login_manager.user_loader(load_user)

    # Include server-assets in the jinja loader
    jinja_loader = FileSystemLoader(path.join(path.dirname(__file__), loader_path) for loader_path in [
        'templates',
        'server-assets',
    ])
    app.jinja_loader = jinja_loader


    from .views import blog
    from .views import apis
    from .views import misc
    from .views import lcp
    from .auth.views import mod as auth_mod

    # Register blueprints
    app.register_blueprint(blog.mod)
    app.register_blueprint(apis.mod)
    app.register_blueprint(auth_mod)
    app.register_blueprint(misc.mod)
    app.register_blueprint(lcp.mod)

    @app.before_request
    def add_user():
        g.user = current_user
        if current_user.is_authenticated:
            identity_changed.send(current_app._get_current_object(), identity=Identity(current_user.id))

    from . import context_processors

    app.context_processor(context_processors.default)
    app.context_processor(context_processors.config)
    app.context_processor(context_processors.revved_url_for)

    @app.errorhandler(500)
    def server_error(error):
        generic_error_handler(error)
        return 'Oops', 500

    @app.errorhandler(403)
    def forbidden(error):
        return "Your kung-foo is insufficient to do this.", 403

    @app.route('/images/<filename>')
    def images(filename):
        return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

    return app


def _configure_app(app, **extra_config):
    # Load the core settings:
    core_settings = path.join(path.abspath(path.dirname(__file__)), 'settings.py')
    app.config.from_pyfile(core_settings)

    # Load from envvars (needed for Heroku-like environments)
    for key, val in os.environ.items():
        if not key.startswith('BLAG_'):
            continue

        key = key[len('BLAG_'):]
        if val.lower() in ('t', 'true'):
            val = True
        elif val.lower() in ('f', 'false'):
            val = False

        try:
            val = int(val)
        except:
            pass

        app.config[key] = val

    # Load stuff from local config:
    config_from_environ = os.environ.get('BLAG_CONFIG_FILE')
    if config_from_environ:
        print('Loading config from %s' % config_from_environ)
        app.config.from_pyfile(path.join(os.getcwd(), config_from_environ))

    # Override the config with anything set directly in the creation call:
    app.config.update(extra_config)

    # Set filerevisions
    filerevs_path = path.join('server-assets', 'filerevs.json')
    try:
        with app.open_resource(filerevs_path) as filerevs_fh:
            filerevs = json.load(filerevs_fh)
            app.config['FILEREVS'] = filerevs
    except IOError:
        print('No filerevs found, continuing without')
        app.config['FILEREVS'] = {}

    app.static_folder = app.config.get('STATIC_FILES')


def _init_logging(app):
    log_config_dest = app.config.get('LOG_CONF_PATH')
    if log_config_dest:
        with open(log_config_dest) as log_config_file:
            logging.config.dictConfig(yaml.load(log_config_file))


def generic_error_handler(exception):
    """ Log exception to the standard logger. """
    log_msg = textwrap.dedent("""Error occured!
        Path:                 %s
        Params:               %s
        HTTP Method:          %s
        Client IP Address:    %s
        User Agent:           %s
        User Platform:        %s
        User Browser:         %s
        User Browser Version: %s
        HTTP Headers:         %s
        Exception:            %s
        """ % (
            request.path,
            request.values,
            request.method,
            request.remote_addr,
            request.user_agent.string,
            request.user_agent.platform,
            request.user_agent.browser,
            request.user_agent.version,
            request.headers,
            exception
        )
    )
    _logger.exception(log_msg)

blag/views/apis.py
from birdy.twitter import AppClient
from flask import Blueprint, current_app, Response, request

import requests
import ujson as json

mod = Blueprint('blag_apis', __name__)

@mod.route('/tweets/<tweet_id>')
def tweet(tweet_id):
    client = AppClient(
        current_app.config['TWITTER_CLIENT_ID'],
        current_app.config['TWITTER_CLIENT_SECRET'],
    )
    client.get_access_token()
    resource = client.api.statuses.show
    response = resource.get(id=tweet_id)
    data = json.dumps(response.data)
    return Response(data, mimetype='application/json')

blag/views/blog.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from .. import db
from ..blocks import render_block
from ..context_processors import _revved_url_for as revved_url_for
from ..models import BlogPost, BlogPostForm, TagForm
from ..auth import admin_permission

from flask import (Blueprint, render_template, request, flash, redirect, url_for,
    current_app, Response, abort)
from flask_login import login_required
from jinja2.filters import do_striptags, do_truncate
from logging import getLogger
from os import path
from werkzeug import secure_filename
from werkzeug.contrib.atom import AtomFeed
from PIL import Image

import ujson as json
import json as _slow_json
import sqlalchemy as sa

mod = Blueprint('blag', __name__)

_logger = getLogger('blag.blog')

@mod.route('/')
def main():
    entries = BlogPost.query.order_by(BlogPost.datetime_added.desc()).all()
    return render_template('home.html', entries=entries)


@mod.route('/blog', methods=['GET', 'POST'])
@login_required
@admin_permission.require(403)
def new_post():
    _logger.debug(request.form)
    form = BlogPostForm()
    if form.validate_on_submit():
        post = BlogPost()
        form.populate_obj(post)
        post.render()
        db.session.add(post)
        flash("New entry saved!", 'success')
        return redirect(url_for('.main'))
    status_code = 200 if request.method == 'GET' else 400
    context = {
        'form': form,
        'async_stylesheets': [
            revved_url_for('static', filename='css/writeEntry.css'),
        ],
    }
    return render_template('new_entry.html', **context), status_code


@mod.route('/blag/<int(min=1, max=99):post_id>')
def post_details_old(post_id):
    # Redirect the old posts with just id-based lookups to slugs
    post = BlogPost.query.get_or_404(post_id)
    year = post.datetime_added.year
    return redirect(post.url())


@mod.route('/<int:year>/<slug>')
def post_details(year, slug):
    post = post_from_year_and_slug_or_404(year, slug)
    description = do_truncate(current_app.jinja_env, do_striptags(post.rendered_content))
    title = post.title
    return render_template('post_details.html', post=post, description=description, title=title)


def post_from_year_and_slug_or_404(year, slug):
    year_filter = sa.extract('year', BlogPost.datetime_added)
    post = BlogPost.query.filter(year_filter==year, BlogPost.slug==slug).first()
    if not post:
        abort(404)
    return post


@mod.route('/<int(min=1000, max=9999):year>')
def posts_in_year(year):
    year_filter = sa.extract('year', BlogPost.datetime_added)
    posts = BlogPost.query.filter(year_filter==year).all()
    return render_template('list_posts.html', posts=posts, year=year)


@mod.route('/<int(min=1000, max=9999):year>/<slug>/edit', methods=('GET', 'POST'))
@login_required
@admin_permission.require(403)
def edit_post(year, slug):
    post = post_from_year_and_slug_or_404(year, slug)
    form = BlogPostForm(obj=post)
    if form.validate_on_submit():
        form.populate_obj(post)
        post.render()
        flash('Post modified successfully', 'success')
        return redirect(post.url())
    context = {
        'form': form,
        'post': post,
        'async_stylesheets': [
            revved_url_for('static', filename='css/writeEntry.css'),
        ],
    }
    return render_template('edit_entry.html', **context)


@mod.route('/blag/<int:post_id>', methods=['DELETE'])
@login_required
@admin_permission.require(403)
def delete_post(post_id):
    post = BlogPost.query.get_or_404(post_id)
    db.session.delete(post)
    return 'Post deleted', 200


@mod.route('/images', methods=['POST'])
@login_required
@admin_permission.require(403)
def image_upload():
    _logger.info(request.data)
    _logger.info(request.files)
    file = request.files['attachment[file]']
    filename = secure_filename(file.filename)
    file_path = path.join(current_app.config['UPLOAD_FOLDER'], filename)
    file.save(file_path)
    data = {
        'path': url_for('images', filename=filename),
        'url': url_for('images', filename=filename),
        'name': filename,
    }
    try:
        data['dimensions'] = Image.open(file_path).size
    except:
        _logger.exception('Failed to get dimensions from image')
    return Response(json.dumps({
        'file': data,
        'msg': 'Image upload OK',
    }), mimetype='application/json')


@mod.route('/styleguide')
def styleguide():
    blocks = [
        {
            "type": "text",
            "data": {
                "text": "# This is the first header\n\nThis is a normal text block.\n\n\n\nIt might contain several paragraphs, and should in general contain lots of markdown-formatted text.\n\n"
            }
        },
        {
            "type": "quote",
            "data": {
                "text": "> This is a short quote.",
                "cite": "Tarjei Husøy"
            }
        },
        {
            "type": "tweet",
            "data": {
                "user": {
                    "profile_image_url": "http://pbs.twimg.com/profile_images/3487712650/0d41ed3269413e459aa6f61b385e84e7_normal.jpeg",
                    "profile_image_url_https": "https://pbs.twimg.com/profile_images/3487712650/0d41ed3269413e459aa6f61b385e84e7_normal.jpeg",
                    "screen_name": "Susmumrik",
                    "name": "Susanne Egset"
                },
                "id": "396758841528156160",
                "text": "Religion is dead. #zombieapocalypse hit the #vatican http://t.co/OWHhvVdR5j",
                "created_at": "Sat Nov 02 22:00:53 +0000 2013",
                "status_url": "https://twitter.com/Susmumrik/status/396758841528156160"
            }
        },
        {
            "type": "heading",
            "data": {
                "text": "This is my heading"
            }
        },
        {
            "type": "quote",
            "data": {
                "text": "> This is a quote consisting of several paragraphs.\n> \n> Just because some people saylots of sensible things.\n",
                "cite": "Everyone"
            }
        },
        {
            "type": "ul",
            "data": {
                "text":" - Bulletpoint 1\n - Bulletpoint 2\n - List are effing awesome\n"
            }
        },
        {
            "type": "code",
            "data": {
                "language": "python",
                "text": "# This is a code example:\n#!/usr/bin/env python\napp = Flask(__name__)\n\n@app.route(\'/\')\ndef home():\n    return render_template(\'home.html\')\n"
            }
        },
        {
            "type": "video",
            "data": {
                "source": "vimeo",
                "remote_id": "48177187"
            }
        },
        {
            "type": "video",
            "data": {
                "source": "youtube",
                "remote_id": "Fq00mCqBMY8"
            }
        },
        {
            "type": "sourced_quote",
            "data": {
                "text": "Today has been crazy.",
                "author": "Markus",
                "source": "https://suonto.com/"
            }
        },
        {
            "type": "gallery",
            "data": [
                {
                    "type": "image",
                    "data": {
                        "msg": "Image upload OK",
                        "imageUrl": "DSC_0334.jpg"
                    }
                },
                {
                    "type": "image",
                    "data": {
                        "msg": "Image upload OK",
                        "imageUrl": "DSC_0333.jpg"
                    }
                },
                {
                    "type": "image",
                    "data": {
                        "msg": "Image upload OK",
                        "imageUrl": "DSC_0332.jpg"
                    }
                },
                {
                    "type": "image",
                    "data": {
                        "msg": "Image upload OK",
                        "imageUrl": "DSC_0331.jpg"
                    }
                }
            ]
        }

    ]
    def pprint(block):
        return _slow_json.dumps(block, indent=4)
    return render_template('styleguide.html', blocks=blocks, pprint=pprint, render_block=render_block)


@mod.route('/blag.atom')
def blag_feed():
    feed = AtomFeed('Tarjei Husøy’s blag',
                    feed_url=request.url, url=request.url_root, author='Tarjei Husøy',
                    icon=url_for('static', filename='img/atom_icon.jpg', _external=True),
                    logo=url_for('static', filename='img/atom_logo.jpg', _external=True))
    articles = BlogPost.query.order_by(BlogPost.datetime_added.desc()).limit(15).all()
    for article in articles:
        feed.add(article.title, article.rendered_content,
                 content_type='html',
                 url=article.url(external=True),
                 updated=article.datetime_added,
                 published=article.datetime_added)
    return feed.get_response()

blag/views/lcp.py
import ujson as json

from flask import (Blueprint, current_app, Response, request, render_template,
    jsonify, redirect, url_for, abort)
from flask_login import login_required
from sqlalchemy.orm import contains_eager

from .. import db
from ..auth import admin_permission
from ..models import Hike, HikeDestination, HikeDestinationForm, HikeForm

mod = Blueprint('lcp', __name__)

@mod.route('/lcp')
def lcp():
    return render_template('lcp.html',
        google_maps_api_key=current_app.config['GOOGLE_MAPS_API_KEY'])


@mod.route('/lcp/peaks')
def lcp_peaks():
    hikes = Hike.query\
        .distinct(Hike.destination_id)\
        .join(Hike.destination)\
        .options(contains_eager(Hike.destination))\
        .filter(HikeDestination.is_summit==True)
    serialized = [hike.destination.to_json() for hike in hikes]
    return jsonify({
        'peaks': serialized,
    })


@mod.route('/lcp/destinations', methods=['POST'])
@login_required
@admin_permission.require(403)
def lcp_destinations():
    name = request.form.get('name') or abort(400)
    altitude = request.form.get('altitude') or abort(400)
    is_summit = 'is_summit' in request.form
    coordinates = request.form.get('high_point_coord') or abort(400)

    coordinates = coordinates.split(',')
    if not len(coordinates) == 2:
        abort(400)
    coordinates = [float(point) for point in coordinates]


    destination = HikeDestination(
        name=name,
        altitude=int(altitude),
        high_point_coord='POINT(%f %f)' % tuple(coordinates),
        is_summit=is_summit,
    )
    db.session.add(destination)
    return redirect(url_for('.lcp'))


@mod.route('/lcp/destinations')
@login_required
@admin_permission.require(403)
def lcp_destination_form():
    form = HikeDestinationForm()
    return render_template('lcp_destination.html', form=form)


@mod.route('/lcp/hikes', methods=['GET', 'POST'])
@login_required
@admin_permission.require(403)
def lcp_hikes():
    form = HikeForm()
    if form.validate_on_submit():
        hike = Hike()
        hform = HikeForm()
        hform.populate_obj(hike)
        # The ModelFieldList doesn't properly populate this field
        hike.destination_id = request.form['destination_id']
        db.session.add(hike)
        return redirect(url_for('.lcp'))
    return render_template('lcp_hike.html', form=form)

blag/views/misc.py
from flask import Blueprint

mod = Blueprint('misc', __name__)

@mod.route('/robots.txt')
def robots_txt():
    headers = {
        'Cache-Control': 'public, max-age=600',
    }
    return 'User-agent: *\nDisallow: /\n', 200, headers

blag/templates/base.html
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article#">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ title|default("Blag") }}</title>
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        {% include 'core.css' %}
    </style>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="source" href="https://github.com/thusoy/blag">
    <link rel="alternate" href="{{ url_for('blag.blag_feed') }}" title="Recent blag posts" type="application/atom+xml">
    {% block open_graph %}
        <meta property="og:title" content="thusoy.com">
        <meta property="og:description" content="{{ description }}">
        <meta property="og:type" content="website">
        <meta property="og:image" content="{{ url_for('static', filename='img/header.jpg', _external=True) }}">
        <meta property="og:url" content="https://thusoy.com">
    {% endblock %}

    {% block extra_head %}
    {% endblock %}
</head>
<body>
    <!--[if lt IE 7]>
        <p class="msg">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <header role="navigation">
        <a href="/">
            <img class="banner img-responsive" height="315" width="1000" src="{{ url_for('static', filename='img/header.jpg') }}">
        </a>
        {% if g.user.is_authenticated %}
            <span class="greeting">Hi there, {{ g.user.first_name }}!</span>
        {% endif %}
        <img class="logo img-circle" src="{{ url_for('static', filename='img/logo2.jpg') }}">
    </header>

    {% for category, msg in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ category }}">
            {{ msg }}
        </div>
    {% endfor %}

    <div class="container">
        {%- block content %}
        {% endblock %}
    </div>

    <script async src="{{ url_for('static', filename='js/main.min.js') }}"></script>

    {% block scripts %}
    {% endblock %}

    {%- if debug %}
        <script async src="http://localhost:35729/livereload.js"></script>
    {% endif -%}

    <script>
        {% include 'inline.js' %}
        loadCSS("{{ url_for('static', filename='css/styles.css') }}");
        {%- for async_stylesheet in async_stylesheets %}
        loadCSS('{{ async_stylesheet }}');
        {%- endfor %}
    </script>
    <noscript>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        {%- for async_stylesheet in async_stylesheets %}
        <link rel="stylesheet" href="{{ async_stylesheet }}">
        {%- endfor %}
    </noscript>
</body>
</html>

blag/templates/edit_entry.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <h1>Edit post</h1>

        <form method="post" action="{{ url_for('.edit_post', year=post.year, slug=post.slug) }}">

            {{ form.render() }}

            <input type="submit" class="btn btn-primary pull-right">
        </form>
    </section>
{% endblock %}


{% block scripts %}
    <script async src="{{ url_for('static', filename='js/writePost.min.js') }}"></script>
{% endblock %}

blag/templates/home.html
{% extends 'base.html' %}

{% block content %}
    {%- for entry in entries %}
        <section>
            <article>
                <span class="byline">{{ entry.datetime_added.strftime('%Y-%m-%d %H:%M') }}</span>

                <a href="{{ entry.url() }}"><h1>{{ entry.title }}</h1></a>


                {{ entry.rendered_content|safe }}

            </article>
        </section>
    {% endfor %}
{% endblock %}

blag/templates/lcp.html
{% extends 'base.html' %}

{% block extra_head %}
<style>
    #map {
        height: 600px;
        width: 100%;
        margin-bottom: 50px;
    }
</style>
{% endblock %}

{% block content %}

<p>
    I collect peaks, this is my list. Note that my definition of "peak" here is gratuitious, I've included both hills, almost-reached-the-summit adventures, and needles without a name on the map. The point is the joy of discovery and adventure and getting out, it's not a competition. Collecting motivates me to do more and go new places.
</p>

<p>
    <small>LCP: List of Completed Peaks, the term used where I first found someone else's list like this</small>
</p>

<div id="map">
</div>

{% endblock %}


{% block scripts %}
<script src="{{ url_for('static', filename='js/lcp.min.js') }}"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&callback=initMap&libraries=visualization"></script>

{% endblock %}

blag/templates/lcp_destination.html
{% extends 'base.html' %}

{% block content %}

<p>
    Add destination:
</p>

<form method="post" action="{{ url_for('.lcp_destinations') }}">
    {{ form.render() }}
    <input type="submit" value="Add destination">
</form>

{% endblock %}

blag/templates/lcp_hike.html
{% extends 'base.html' %}

{% block content %}

<p>
    Add hike:
</p>

<form method="post" action="{{ url_for('.lcp_hikes') }}">
    {{ form.render() }}
    <input type="submit" value="Add hike">
</form>

{% endblock %}

blag/templates/list_posts.html
{% extends 'base.html' %}

{% block content %}

{% if posts %}
    <ul>
        {% for post in posts %}

            <li>
                <a href="{{ post.url() }}">{{ post.title }}</a><span>,
                published {{ post.datetime_added.strftime('%Y-%m-%d') }}
                </span>
            </li>

        {% endfor %}
    </ul>

{% else %}
    <p>
        No posts found for {{ year }}, I'm afraid.
    </p>
{% endif %}

{% endblock %}

blag/templates/map.html
<!doctype html>
<html>
<head>
  <title>Hike map</title>
  <style>
    html, body, #map {
      height: 100%;
    }
  </style>
  <script src="http://www.openlayers.org/api/OpenLayers.js"></script>
  <script>
    var map,vectorLayer,selectedFeature;
    var lat = 63.22834606600802;
    var lon = 12.346664959716744;
    var zoom = 14;
    var curpos = new Array();
    var position;
    var apiKey = '{{ thunderforest_api_key }}';

    var fromProjection = new OpenLayers.Projection("EPSG:4326");   // Transform from WGS 1984
    var toProjection = new OpenLayers.Projection("EPSG:900913"); // to Spherical Mercator Projection
    var cntrposition = new OpenLayers.LonLat(lon, lat).transform(fromProjection, toProjection);

    OpenLayers.Layer.OSM.HikeMap = OpenLayers.Class(OpenLayers.Layer.OSM, {
      initialize: function(name, options) {
        var urls = [
          "http://a.tile.thunderforest.com/outdoors/${z}/${x}/${y}.png",
          "http://b.tile.thunderforest.com/outdoors/${z}/${x}/${y}.png",
          "http://c.tile.thunderforest.com/outdoors/${z}/${x}/${y}.png",
        ];
        for (var i = 0; i < urls.length; i++) {
            urls[i] += '?apikey=' + apiKey;
        }
        var newArguments = [name, urls, options];
        OpenLayers.Layer.OSM.prototype.initialize.apply(this, newArguments);
      },
    });

    function init() {
      map = new OpenLayers.Map("map");
      var cycleLayer = new OpenLayers.Layer.OSM.HikeMap("Hiking Map");

      map.addLayer(cycleLayer);
      map.setCenter(cntrposition, zoom);

      var click = new OpenLayers.Control.Click();
      map.addControl(click);

      click.activate();
    };

    OpenLayers.Control.Click = OpenLayers.Class(OpenLayers.Control, {
      defaultHandlerOptions: {
        'single': true,
        'double': false,
        'pixelTolerance': 0,
        'stopSingle': false,
        'stopDouble': false
      },

      initialize: function(options) {
        this.handlerOptions = OpenLayers.Util.extend({}, this.defaultHandlerOptions);
        OpenLayers.Control.prototype.initialize.apply(this, arguments);
        this.handler = new OpenLayers.Handler.Click(this, {
          'click': this.trigger
        }, this.handlerOptions);
      },

      trigger: function(e) {
        var lonlat = map.getLonLatFromPixel(e.xy);
        lonlat1= new OpenLayers.LonLat(lonlat.lon,lonlat.lat).transform(toProjection,fromProjection);
        alert(lonlat1.lat + ", " + lonlat1.lon);
      },
    });
  </script>
</head>

<body onload='init();'>
    <div id="map"></div>
</body>

</html>

blag/templates/me.html
{% extends 'base.html' %}

{% block content %}

    <section>
        <p>
            So, this is me.
        </p>
    </section>

{% endblock %}

blag/templates/new_entry.html
{% extends 'base.html' %}

{% block content %}
    <section>

        <h1>New blogpost</h1>

        <form method="post" action="/blog">

            {{ form.render() }}

            <input type="submit" class="btn btn-primary pull-right">
        </form>
    </section>
{% endblock %}


{% block scripts %}
    <script async src="{{ url_for('static', filename='js/writePost.min.js') }}"></script>
{% endblock %}

blag/templates/new_recommendation.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" action="{{ url_for('.new_recommendation') }}">
        {{ form.render() }}

        <input type="submit" value="Add">
    </form>

{% endblock %}

blag/templates/projects.html
{% extends 'base.html' %}

{% block content %}

    <section>

        <h1>Projects</h1>

        <p>
            Some stuff I've done previously and some I'm still doing:
        </p>


        <h2>Robert Paulson: Lego mindstorms robot and website</h2>

        <a href="http://bob.thusoy.com">
            <img src="{{ url_for('static', filename='img/robert-paulson.jpg') }}" alt="Robert Paulson">
        </a>

        <p>
            A Lego Mindstorms robot I built with <a href="https://github.com/afflux">@afflux</a> and <a href="https://www.facebook.com/damien.roeder">@damien.roeder</a>. The intention was to win a tennis-like robot tournament. Design and strategy felt solid, but when tournament day came we were haunted by previously unseen bugs and erratic behavior, and finished somewhere in the middle.
        </p>

        <p>
            The blog was based on a home-rolled static blog generator, based on frozen-flask, hosted on GitHub Pages.
        </p>

        <h2>Website for NTNUI Telemark/Alpint: ntnuita.no</h2>

        <a href="http://ntnuita.no">
            <img src="{{ url_for('static', filename='img/ntnuita.jpg') }}" alt="ntnuita.no">
        </a>

        <p>
            Started tinkering with new websites for my sports crew in Trondheim back in 2011, then running on Google App Engine. We've since migrated to AWS, but still running much of the same Django codebase as back then. Still in development.
        </p>

        <h2>Eurecom Movie Club</h2>

        <img src=""
    </section>

{% endblock %}

blag/templates/recommendations.html
{% extends 'base.html' %}

{% block content %}

Stuff I love.

{% for recommendation in recommendations %}

    <h2>
        <a href="{{ recommendation.href }}">
            {{ recommendation.title }}
        </a>
    </h2>

    <span class="about-recommendation">
        {{ recommendation.medium }} by {{ recommendation.credits }}.
    </span>



{% endfor %}

{% endblock %}

blag/templates/styleguide.html
{% extends 'base.html' %}

{% block content %}
    <h1>Styleguide</h1>

    <p>
        A look at how different block types in posts are defined, rendered, and displayed.
    </p>

    <p>
        Jump to block:
    </p>
    {% for block in blocks %}
        <a href="#{{ block.type }}">{{ block.type }}</a>
    {% endfor %}

    {% for block in blocks %}
        <h2 id="{{ block.type }}">{{ block.type }}</h2>

        <strong>JSON</strong>
        <pre>
{
  "type": "{{ block.type }}",
  "data": {{ pprint(block.data) }},
}</pre>

    <strong>HTML</strong>
    <pre>
{{ render_block(block) }}
    </pre>

    <strong>Display</strong>
    {{ render_block(block)|safe }}
    {% endfor %}

{% endblock %}